language: node_js
node_js:
  - lts/*
addons:
  ssh_known_hosts: 35.233.171.1
script:
  - npm run build
before_deploy:
  - openssl aes-256-cbc -K $encrypted_fd75b0287618_key -iv $encrypted_fd75b0287618_iv
    -in deploy-rsa-key.enc -out /tmp/deploy-rsa-key -d
  - chmod 600 /tmp/deploy-rsa-key
  - eval `ssh-agent`
  - ssh-add /tmp/deploy-rsa-key
deploy:
  provider: script
  skip_cleanup: true
  script:
    - rsync -azvP build/ kailangfu@35.233.171.1:/home/kailangfu/www/gskse.com/
    - kill $SSH_AGENT_PID
  on:
    branch: master